version: '2'

services:

  jboss-cts-activemq:
    container_name: jboss-cts-activemq
    hostname: jboss.cts.activemq.com
    image: nexussrv.com:18444/webcenter/activemq:5.14.3
    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"
    environment:
      ACTIVEMQ_CONFIG_NAME: jboss.cts.activemq.com
      ACTIVEMQ_CONFIG_DEFAULTACCOUNT: 'false'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: Passw0rd
    networks:
      cts-jboss-ntw:
        aliases:
          - jboss.cts.activemq.com

  jboss-cts-sybase:
    container_name: jboss-cts-sybase
    hostname: dksybase
    image: nexussrv.com:18444/sch-sybase:15.7
    ports:
      - "45000:5000"
    environment:
      SYBASE_USER: sa
      SYBASE_PASSWORD: password
    networks:
      cts-jboss-ntw:
        aliases:
          - jboss.cts.sybase.com

  jboss-cts-sqlserver:
    container_name: jboss-cts-sqlserver
    hostname: jboss.cts.sqlserver.com
    image: 'nexussrv.com:18444/dev/was-9/cts-4/sqlserver:2017'
    environment:
      - 'ACCEPT_EULA=Y'
      - 'SA_PASSWORD=mssqlServer1433'
    ports:
      - '41433:1433'
    networks:
      cts-jboss-ntw:
        aliases:
          - jboss.cts.sqlserver.com

  jboss-cts-ssn:
    container_name: jboss-cts-ssnsrv
    hostname: jboss.cts.ssnserver.com
    image: nexussrv.com:18444/cobis-ssnsrv
    stdin_open: true
    tty: true
    ports:
      - "46005:6005"
    networks:
      cts-jboss-ntw:
        aliases:
          - jboss.cts.ssnserver.com

  jboss-cts:
    container_name: jboss-cts
    hostname: jboss.cts.com
    image: nexussrv.com:18444/cwc/tomcat:latest
    mac_address: 02-42-AC-13-00-08
    environment:
      CTS_VERSION: 4.5.0
      IEN_VERSION: 4.6.2
      URL_REPOSITORY_INSTALLER: "http://192.168.219.33:9091"
    ports:
      - "48080:8080"
      - "48443:8443"
      - "49990:9990"
      - "49993:9993"
    depends_on:
      - jboss-cts-activemq
      - jboss-cts-sybase
      - jboss-cts-sqlserver
      - jboss-cts-ssn
    networks:
      cts-jboss-ntw:
        aliases:
          - jboss.cts.com

  jboss-cts-ftp:
    container_name: jboss-cts-ftp
    hostname: jboss.cts.sftpsrv.com
    image: nexussrv.com:18444/atmoz/sftp
    ports:
        - "4222:22"
    command: foo:Passw0rd:1001
    privileged: true
    volumes:
      - ./sftp/upload:/home/foo/upload
      - ./sftp/Automoviles:/home/foo/Automoviles
      - ./sftp/GenerateCar:/home/foo/GenerateCar
    networks:
     cts-jboss-ntw:
        aliases:
          - jboss.cts.sftpsrv.com

networks:
  cts-jboss-ntw:
